### ISSUE TITLE
Incompatibility with Sodium 0.5.4 [1.20.2]

### ISSUE THREAD

**Issue by semjonsona** [ferriarnus/VivecraftForge#231]
Hello.
I've discovered that recent Sodium 0.5.4 needs some more compatibility code to accommodate for. When I start Minecraft, the game loading screen never disappear. This is what I see in the logs folder:

```[11:13:52] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.24
[11:13:52] [main/INFO]: Loading 17 mods:
	- fabricloader 0.14.24
	- java 17
	- minecraft 1.20.2
	- sodium 0.5.4
	   |-- fabric-api-base 0.4.32+fce67b3203
	   |-- fabric-block-view-api-v2 1.0.0+73761d2e03
	   |-- fabric-rendering-data-attachment-v1 0.3.38+73761d2e9a
	   |-- fabric-rendering-fluids-v1 3.0.29+f4b7e42403
	   \-- fabric-resource-loader-v0 0.11.10+86b1264503
	- vivecraft 1.20.2-1.1.5
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- fabric-command-api-v2 2.2.14+86b12645a0
	   |-- org_lwjgl_lwjgl-openvr 3.3.1
	   |-- org_lwjgl_lwjgl-openvr_natives-linux 3.3.1
	   |-- org_lwjgl_lwjgl-openvr_natives-macos 3.3.1
	   \-- org_lwjgl_lwjgl-openvr_natives-windows 3.3.1
[11:13:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/semjon/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:13:52] [main/INFO]: Compatibility level set to JAVA_17
[11:13:52] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[11:13:52] [main/INFO]: Vivecraft: applying 'dynamicfps' fixes
[11:13:52] [main/INFO]: Vivecraft: applying 'sodium' fixes
[11:13:52] [main/INFO]: Vivecraft: applying 'sodium' fixes
[11:13:53] [main/INFO]: Vivecraft: applying 'modmenu' fixes
[11:13:53] [main/INFO]: Vivecraft: applying 'physicsmod' fixes
[11:13:53] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/screenhandler/client/ClientNetworking (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/screenhandler/client/ClientNetworking)
[11:13:53] [main/WARN]: @Mixin target net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking was not found vivecraft.fabric.mixins.json:screenhandler.client.FabricClientNetworkingVRMixin from mod vivecraft
[11:13:53] [main/INFO]: Searching for graphics cards...
[11:13:53] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce GTX 1080 Ti, version=DriverVersion=31.0.15.4601]
[11:13:53] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[11:13:53] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[11:13:58] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 212 milliseconds
[11:14:01] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[11:14:02] [Render thread/INFO]: Setting user: [REDACTED]
[11:14:02] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[11:14:02] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[11:14:03] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[11:14:03] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
[11:14:03] [Render thread/INFO]: OpenGL Version: 3.2.0 NVIDIA 546.01
[11:14:03] [Render thread/WARN]: Checking for problematic loaded Win32 modules... (this may take a moment)
[11:14:03] [Render thread/INFO]: Found non-pack entry 'C:\Users\semjon\AppData\Roaming\.minecraft\resourcepacks\old', ignoring
[11:14:04] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (fabric-api-base, fabric-block-view-api-v2, fabric-command-api-v2, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, sodium, vivecraft)
[11:14:04] [Worker-Main-3/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[11:14:04] [VivecraftUpdateThread/INFO]: [STDOUT]: Checking for Vivecraft Updates
[11:14:06] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:14:06] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:14:06] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on [REDACTED]
[11:14:06] [Render thread/INFO]: Sound engine started
[11:14:06] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[11:14:06] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[11:14:06] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:14:06] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:14:06] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[11:14:06] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:14:06] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[11:14:06] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:14:06] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:14:07] [Render thread/INFO]: Vivecraft: Optifine not detected
[11:14:07] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NoSuchFieldError: quads
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[fabric-loader-0.14.24-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
Caused by: java.lang.NoSuchFieldError: quads
	at org.vivecraft.mod_compat_vr.sodium.SodiumHelper.copyModelCuboidUV(SodiumHelper.java:58) ~[vivecraft-1.20.2-1.1.5-fabric.jar:?]
	at org.vivecraft.client.render.VRPlayerModel_WithArms.<init>(VRPlayerModel_WithArms.java:54) ~[vivecraft-1.20.2-1.1.5-fabric.jar:?]
	at org.vivecraft.client.render.VRPlayerRenderer.<init>(VRPlayerRenderer.java:29) ~[vivecraft-1.20.2-1.1.5-fabric.jar:?]
	at net.minecraft.class_898.handler$zfi000$vivecraft$reload(class_898.java:1106) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:415) ~[client-intermediary.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 12 more
[11:14:07] [Render thread/INFO]: Found non-pack entry 'C:\Users\semjon\AppData\Roaming\.minecraft\resourcepacks\old', ignoring
[11:14:07] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (fabric-api-base, fabric-block-view-api-v2, fabric-command-api-v2, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-resource-loader-v0, fabricloader, sodium, vivecraft)
[11:14:07] [Worker-Main-3/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[11:14:08] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:14:08] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:14:08] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on [REDACTED]
[11:14:08] [Render thread/INFO]: Sound engine started
[11:14:08] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[11:14:08] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[11:14:08] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:14:08] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:14:08] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[11:14:08] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:14:08] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[11:14:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:14:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:14:32] [Render thread/INFO]: Stopping!
```

Thank you for this awesome mod!

**Comment by semjonsona** [comment]
Seems to work in 1.1.6. Thank you!

**Comment by fayer3** [comment]
oh yeah forgot to close this, sorry
