### ISSUE TITLE
Bedrockify causes menuworld fail

### ISSUE THREAD

**Issue by fayer3** [ferriarnus/VivecraftForge#235]
```
[13:20:07] [Worker-Main-8/ERROR]: Exception thrown when building main menu world, falling back to old menu room. 
 Tesselating block model
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: net.minecraft.class_148: Tesselating block model
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_776.method_3355(class_776.java:68)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at org.vivecraft.client_vr.menuworlds.MenuWorldRenderer.buildGeometry(MenuWorldRenderer.java:391)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at org.vivecraft.client_vr.menuworlds.MenuWorldRenderer.lambda$buildNext$2(MenuWorldRenderer.java:334)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_37908()" because "client.field_1724" is null
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at me.juancarloscp52.bedrockify.client.features.bedrockShading.BedrockBlockShading.getBlockShade(BedrockBlockShading.java:16)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_778.redirect$zkc000$bedrockify$getBlockShade(class_778.java:534)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_778.method_3370(class_778.java:221)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_778.method_3373(class_778.java:111)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_778.method_3374(class_778.java:50)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_776.method_3355(class_776.java:60)
[13:20:07] [Worker-Main-8/INFO]: [STDERR]: 	... 9 more
```

**Comment by Techjar** [comment]
Disabling the world noise feature might be a workaround.
