### ISSUE TITLE
Crash between 1.21-1.1.12-b1-fabric & 1.21-1.1.11-b5-fabric, Obscure Error Message

### ISSUE THREAD

**Issue by Bowswa** [ferriarnus/VivecraftForge#305]
Hello!

I've been working on an update for my modpack, Linked [Here](https://modrinth.com/modpack/imaginary).

The modpack runs will with all currently installed mods in the latest version, but updated to 1.1.12 b1 will precede to crash. 

I'm too busy working on the update to add some more content & update packs n stuff. I will do some troubleshooting, eliminate conflict possibilities, but i'm making the issue now.

Error Code: 
```Description: Unexpected error
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 12
at java.base/java.util.Spliterators.checkFromToBounds(Unknown Source)
at java.base/java.util.Spliterators.spliterator(Unknown Source)
at java.base/java.util.Arrays.spliterator(Unknown Source)
at java.base/java.util.Arrays.stream(Unknown Source)
at net.minecraft.class_276.modify$epm000$vivecraft$noViewportChangeOnClear(class_276.java:1629)
at net.minecraft.class_276.method_1230(class_276.java:276)
at me.zziger.obsoverlay.OverlayRenderer.beginFrame(OverlayRenderer.java:68)
at net.minecraft.class_310.handler$dko000$obs_overlay$onRender(class_310.java:20670)
at net.minecraft.class_310.method_1523(class_310.java)
at net.minecraft.class_310.method_1514(class_310.java:882)
at net.minecraft.client.main.Main.main(Main.java:256)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)```

**Comment by fayer3** [comment]
huh

**Comment by fayer3** [comment]
that is a bug with viveccraft itself it seems, didn't think that would happen
bug is here: https://github.com/Vivecraft/VivecraftMod/blob/cde85f81be498f9c9fc9c6368cdcef3cb2ba33bc/common/src/main/java/org/vivecraft/mixin/client/blaze3d/RenderTargetMixin.java#L128
didn't know that would throw an error for smaller stacktraces than that

**Comment by fayer3** [comment]
maybe I should just log the whole thing

**Comment by Bowswa** [comment]
welp looks like i don't have to do any testing lol. thank you very much!
