### ISSUE TITLE
Clicking "Non-vr mode" and switching to VR mode crashes minercaft permantly

### ISSUE THREAD

**Issue by PeckingWater** [ferriarnus/VivecraftForge#319]
After sorting outu all issues with vivecraft and mods, i was at the main menu of minecraft and clicked "non-vr mode" to switch it to "VR-mode" as I was playing in VR, Then the game crashed. Even after deleting and re-installing vivecraft on minecraft laucher and the mod it still keeps crashing, here is the crash report. Any help is appreciated.

 ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-12-04 22:25:56
Description: Unexpected error

java.lang.RuntimeException: Error reading digital data for '/actions/mod/in/vivecraft.key.quickTorch': InvalidHandle
	at org.vivecraft.provider.openvr_jna.MCOpenVR.readDigitalData(MCOpenVR.java:1742) ~[minecrift-1.19.2-jrbudda-VR-2-b8-forge.jar%23220!/:?] {re:classloading}
	at org.vivecraft.provider.openvr_jna.MCOpenVR.readNewData(MCOpenVR.java:1707) ~[minecrift-1.19.2-jrbudda-VR-2-b8-forge.jar%23220!/:?] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?] {}
	at org.vivecraft.provider.openvr_jna.MCOpenVR.updatePose(MCOpenVR.java:1611) ~[minecrift-1.19.2-jrbudda-VR-2-b8-forge.jar%23220!/:?] {re:classloading}
	at org.vivecraft.provider.openvr_jna.MCOpenVR.poll(MCOpenVR.java:417) ~[minecrift-1.19.2-jrbudda-VR-2-b8-forge.jar%23220!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1554) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:963) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:294) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:classloading,xf:Vivecraft:default,re:mixin,xf:Vivecraft:default,pl:mixin:A}
	at net.minecraft.client.main.Main.main(Main.java:56) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:classloading,xf:Vivecraft:default,re:mixin,xf:Vivecraft:default,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.0.7.jar%23106!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.vivecraft.provider.openvr_jna.MCOpenVR.readDigitalData(MCOpenVR.java:1742) ~[minecrift-1.19.2-jrbudda-VR-2-b8-forge.jar%23220!/:?] {re:classloading}
	at org.vivecraft.provider.openvr_jna.MCOpenVR.readNewData(MCOpenVR.java:1707) ~[minecrift-1.19.2-jrbudda-VR-2-b8-forge.jar%23220!/:?] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?] {}
	at org.vivecraft.provider.openvr_jna.MCOpenVR.updatePose(MCOpenVR.java:1611) ~[minecrift-1.19.2-jrbudda-VR-2-b8-forge.jar%23220!/:?] {re:classloading}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, [MEGA] Ghoulcraft 10-22-20.zip, Invisible Item Frame Pack_1.19.4-1.1.zip, Mizunos 16 Craft JE CIT_1.19.4-1.1.zip, Mizunos 16 Craft JE_1.19.4-1.1.zip, Better+Leaves+Add-on+V2.9.1-1.19 (1).zip
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vivecraft.mixins.json:client.ResourceLoadStateTrackerMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:3374) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:992) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,xf:Vivecraft:default,re:classloading,pl:accesstransformer:B,xf:Vivecraft:default,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:294) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:classloading,xf:Vivecraft:default,re:mixin,xf:Vivecraft:default,pl:mixin:A}
	at net.minecraft.client.main.Main.main(Main.java:56) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:classloading,xf:Vivecraft:default,re:mixin,xf:Vivecraft:default,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.0.7.jar%23106!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2393!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1459617792 bytes (1392 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Meta Virtual Monitor
	Graphics card #0 vendor: Meta Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=17.12.55.198
	Graphics card #1 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x21c4
	Graphics card #1 versionInfo: DriverVersion=31.0.15.5123
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37373.22
	Virtual memory used (MB): 25110.03
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 109.79
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -Xms4G -XX:+UseZGC
	Launched Version: vivecraft-1.19.2-jrbudda-VR-2-b8-forge
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 551.23, NVIDIA Corporation
	Window size: 1280x720
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vivecraft'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/[MEGA] Ghoulcraft 10-22-20.zip (incompatible), file/Invisible Item Frame Pack_1.19.4-1.1.zip (incompatible), file/Mizunos 16 Craft JE CIT_1.19.4-1.1.zip (incompatible), file/Mizunos 16 Craft JE_1.19.4-1.1.zip (incompatible), file/Better+Leaves+Add-on+V2.9.1-1.19 (1).zip (incompatible)
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 551.23
	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.0.7.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar Vivecraft TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar  |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6b              |DONE      |Manifest: NOSIGNATURE
		HammerLib-1.19.2-19.1.4.jar                       |HammerLib                     |hammerlib                     |19.1.4              |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |DONE      |Manifest: NOSIGNATURE
		Incendium_v5.1.3a.jar                             |Incendium                     |incendium                     |5.1.0               |DONE      |Manifest: NOSIGNATURE
		colytra-forge-6.0.2+1.19.2.jar                    |Colytra                       |colytra                       |6.0.2+1.19.2        |DONE      |Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.19.2-1.4.5.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.19.2-1.4.5        |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.19-11.1.0.jar                   |Waystones                     |waystones                     |11.1.0              |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.4-mc1.19.2.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.4               |DONE      |Manifest: NOSIGNATURE
		citadel-2.1.1-1.19.jar                            |Citadel                       |citadel                       |2.1.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.19.2-8.2.2.jar                |Traveler's Backpack           |travelersbackpack             |8.2.2               |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.19.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.19.2-1.9.7-forge  |DONE      |Manifest: NOSIGNATURE
		dustydecorations-1.1.0.jar                        |Dusty Decorations             |dustydecorations              |1.19.2-1.1          |DONE      |Manifest: NOSIGNATURE
		configured-2.1.1-1.19.2.jar                       |Configured                    |configured                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.10.jar                  |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.10 |DONE      |Manifest: NOSIGNATURE
		Decorative Blocks-forge-1.19.2-3.0.0.jar          |Decorative Blocks             |decorative_blocks             |3.0.0               |DONE      |Manifest: NOSIGNATURE
		lukis-grand-capitals-1.1.1.jar                    |Luki's Grand Capitals         |mr_lukis_grandcapitals        |1.1.1               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.19-2.3.11.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.11              |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.2-Forge-2.2.2  |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.19.2-1.2.4-forge.jar           |Explorer's Compass            |explorerscompass              |1.19.2-1.2.4-forge  |DONE      |Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |DONE      |Manifest: NOSIGNATURE
		Terralith_1.19.3_v2.3.12.jar                      |Terralith                     |terralith                     |2.3.12              |DONE      |Manifest: NOSIGNATURE
		Display Case-forge-1.19-1.0.3.jar                 |Display Case Mod              |display_case                  |1.0.3               |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar|YUNG's Better Nether Fortresse|betterfortresses              |1.19.2-Forge-1.0.6  |DONE      |Manifest: NOSIGNATURE
		Paraglider-1.19.2-1.7.0.1.jar                     |Paraglider                    |paraglider                    |1.7.0.1             |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.1.1-universal.jar                 |Forge                         |forge                         |43.1.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		vivecraft-1.19.2-1.1.14-forge (2).jar             |Vivecraft                     |vivecraft                     |1.19.2-1.1.14       |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.19-4.2.1381-universal.jar        |The Twilight Forest           |twilightforest                |4.2.1381            |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.19.2-2.6.2.jar                    |Structure Gel API             |structure_gel                 |2.6.2               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |DONE      |Manifest: NOSIGNATURE
		tectonic-forge-1.19-2.3.5a (1).jar                |Tectonic                      |tectonic                      |2.3.5a              |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		DistantHorizons-2.2.1-a-1.19.2-forge-fabric (1).ja|Distant Horizons              |distanthorizons               |2.2.1-a             |DONE      |Manifest: NOSIGNATURE
		handcrafted-forge-1.19.2-2.0.6.jar                |Handcrafted                   |handcrafted                   |2.0.6               |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-6.2.2+1.19.2.jar      |Repurposed Structures         |repurposed_structures         |6.2.2+1.19.2        |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19-2.0.13.jar                         |Moonlight Library             |moonlight                     |1.19-2.0.13         |DONE      |Manifest: NOSIGNATURE
		nekoration-1.19.2-1.8.1.jar                       |Nekoration                    |nekoration                    |1.8.1               |DONE      |Manifest: NOSIGNATURE
		CullLessLeaves-Reforged-1.0.5.jar                 |Cull Less Leaves Reforged     |culllessleaves                |1.0.5               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.12.6+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.6+1.19.2       |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19a-forge-mc1.19.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19a             |DONE      |Manifest: NOSIGNATURE
		MOAdecor+TOYS+1.19.2.jar                          |MOA DECOR: TOYS               |moa_decor_toys                |1.19.2              |DONE      |Manifest: NOSIGNATURE
		MOAdecor+COOKERY+1.19.2.jar                       |MOA DECOR: COOKERY            |moa_decor_cookery             |1.19.2              |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.19.2-1.0.0.jar                   |Easy Villagers                |easy_villagers                |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		pipez-1.19.2-1.0.0.jar                            |Pipez                         |pipez                         |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.6.1-mc1.19.2.jar            |EntityCulling                 |entityculling                 |1.6.1               |DONE      |Manifest: NOSIGNATURE
		tombstone-8.1.0-1.19.1.jar                        |Corail Tombstone              |tombstone                     |8.1.0               |DONE      |Manifest: NOSIGNATURE
		MaFgLib-0.1.6-mc1.19.2.jar                        |MaFgLib                       |malilib                       |0.1.6-mc1.19.2      |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.19.2-1.1.23.jar            |Resourceful Lib               |resourcefullib                |1.1.23              |DONE      |Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		YungsBetterEndIsland-1.19.2-Forge-1.0.jar         |YUNG's Better End Island      |betterendisland               |1.19.2-Forge-1.0    |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v4.3.10-1.19.2-Forge.jar               |Puzzles Lib                   |puzzleslib                    |4.3.10              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		The_Undergarden-1.19.2-0.8.2.jar                  |The Undergarden               |undergarden                   |0.8.2               |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.19.2-Forge-3.2.1.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.1  |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |DONE      |Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.19.2-Forge-1.0.1.jar   |YUNG's Better Jungle Temples  |betterjungletemples           |1.19.2-Forge-1.0.1  |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b01532fd-7b28-4b0d-a17e-858ce4d7177a
	FML: 43.1
	Forge: net.minecraftforge:43.1.1

**Comment by fayer3** [comment]
it looks like you are using both the vivecraft mod and the old installer, only use the mod, not both at once
