### ISSUE TITLE
Render-based crash when attempting to play wynncraft

### ISSUE THREAD

**Issue by 9382** [ferriarnus/VivecraftForge#324]
There seems to be some sort of render-based crash that happens specifically when attempting to connect to Wynncraft. This happened while using the 1.21.1 1.1.14-b2 version of the mod, but this apparently happens on 1.20.4 as well (see [this redit thread](https://www.reddit.com/r/WynnCraft/comments/1fqwjcd/vr_crashing_only_on_wynncraft/))

The main error stacktrace:
```
java.lang.ClassCastException: class net.minecraft.class_8113$class_8122 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_8113$class_8122 and net.minecraft.class_1309 are in unnamed module of loader 'knot' @4d49af10)
	at knot//net.minecraft.class_757.redirect$bbb000$vivecraft$renderpick(class_757.java:3057)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1042)
	at knot//net.minecraft.class_757.method_3192(class_757.java:850)
	at knot//org.vivecraft.client_vr.render.helpers.VRPassHelper.renderSingleView(VRPassHelper.java:49)
	at knot//org.vivecraft.client_vr.render.helpers.VRPassHelper.renderAndSubmit(VRPassHelper.java:328)
	at knot//net.minecraft.class_310.handler$bcn000$vivecraft$renderVRPassesFabric(class_310.java:7210)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1286)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
The entire crash file is given below
[crash-2024-12-17_11.28.17-client.txt](https://github.com/user-attachments/files/18164996/crash-2024-12-17_11.28.17-client.txt)

**Comment by fayer3** [comment]
known issue, it's because wynncraft sets the camera entity to a display entity during cutscenes
will be fixed in the next version

**Comment by 9382** [comment]
got it, and thanks for the fast response. Was this previously reported on the github and I'm just blind?

**Comment by fayer3** [comment]
was reported on the discord

**Comment by fayer3** [comment]
forgot to close that, was fixed with 1.2.0
